version: 2
updates:
  # embedder local:fragments/dependabot-updates.yaml
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  # /embedder
