name: Install embedder
description: Install embedder from the rubykatzen/embedder git repository.
runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: pip install "git+https://github.com/rubykatzen/embedder.git@v0.1"
